export const enum Sprites {
    RobinHood,
    MartyMcFly,
    ForrestGump,
    LukeSkywalker,
    Robocop,
    ObiWanKenobi,
    Neo,
    HarryPotter,
    Batman,
    Superman,
    Leonardo,
    Donatello,
    Raphael,
    MichaelAngelo,
}
